### ISSUE TITLE
docker-compose.yml文件应该缺少了Xray的cert目录映射

### ISSUE THREAD

**Issue by houpi** [crossfw/Air-Universe-DockerInstall#3]
root@hp-amd:~/Air-Universe-DockerInstall# docker logs 24c217566091
Xray 1.4.3 (Xray, Penetrates Everything.) Custom (go1.17.1 linux/amd64)
A unified platform for anti-censorship.
2021/09/14 10:30:57 [Info] infra/conf/serial: Reading config: /etc/xray/config.json
2021/09/14 10:30:57 [Warning] core: Xray 1.4.3 started
2021/09/14 10:31:00 [Error] transport/internet/tls: failed to parse certificate > open /usr/local/share/au/fullchain.pem: no such file or directory

后在docker-compose.yml的xray-airu里volumes段中添加- ./cert/:/usr/local/share/au/后，问题解决

**Comment by crossfw** [comment]
fixed
